spring:
  application:
    name: admin_email_sender_api
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${{ secrets.EMAIL}}
    password: ${{ secrets.PASSWORD}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#    properties:
#      mail:
#        smtp:
#          auth: false
#          starttls:
#            enable: false

server:
  port: 8080