spring:
  application:
    name: admin_email_sender_api
  mail:
    host: db.dokalab.site
    port: 25
    username: ADMIN
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080